[project]
name = "ibm-qiskit-v02x-cert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "marimo>=0.11.17",
    "matplotlib>=3.4.3",
    "pylatexenc>=2.10",
    "qiskit==0.25.3",
    "scikit-build>=0.18.1",
]
